# Generated by Django 4.2.10 on 2025-05-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_bio_userprofile_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='UserMessage',
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='UserNotification',
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Message', 'verbose_name_plural': 'User Messages'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
    ]
