# Generated by Django 4.2.10 on 2025-05-22 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='area_km2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='mayor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipal_manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipality_type',
            field=models.CharField(choices=[('A', 'Category A (Metropolitan)'), ('B', 'Category B (Local)'), ('C', 'Category C (District)')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='municipality',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traditionalcouncil',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traditionalcouncil',
            name='leader_title',
            field=models.CharField(default='Chief', max_length=50),
        ),
        migrations.AddField(
            model_name='traditionalcouncil',
            name='recognition_certificate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='traditionalcouncil',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('dissolved', 'Dissolved')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='village',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be in format: ABC123 (2-3 letters followed by 3 digits)', regex='^[A-Z]{2,3}\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='traditionalcouncil',
            name='term_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
